main: ${PACKAGE}.${NAME}
name: ${NAME}
version: "${VERSION}"
api-version: "1.21"
author: crnobog
description: Mob anti-grief plugin - Prevent mobs from destroying your world
commands:
  nw:
    description: NirnWarden configuration commands
    usage: "/nw <help|status|reload|set>"
    aliases: nirnwarden
permissions:
  nirnwarden.admin:
    description: Allows access to NirnWarden admin commands
    default: op